#!/bin/bash

function delete_local_branches() {
  git branch | grep -v '*\|master\|HEAD' | xargs git branch -D
}

function delete_remote_merged_branches() {
  local check_only=$1
  local delete_branches=()
  for branch in $(git branch -r --merged | grep -v "*\|master\|HEAD" | sed -e "s/origin\///g" | sort | uniq); do
    delete_branches=("${delete_branches[@]}" ":${branch}")
  done
  if [ -z "$(echo ${delete_branches[@]})" ]; then
    echo 'None.'
  elif [ -z "${check_only}" ]; then
    git push origin ${delete_branches[@]}
  else
    echo ${delete_branches[@]}
  fi
}
